In [17]:
%load_ext autoreload
%autoreload 2

In [18]:
import pipeline
import pandas as pd

In [4]:
MY_KEY = 'DGXTHCQ81XKZLWGX'

In [11]:
df = pd.read_csv('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=dfdf&apikey={}&datatype=csv'.format(MY_KEY))

In [21]:
from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.techindicators import TechIndicators
from alpha_vantage.sectorperformance import SectorPerformances
from alpha_vantage.cryptocurrencies import CryptoCurrencies
import matplotlib
import matplotlib.pyplot as plt
import os

In [22]:
ts = TimeSeries(key=os.environ['AV_API_KEY'], output_format='pandas')

In [23]:
meta_data

NameError: name 'meta_data' is not defined

In [24]:
data, meta_data = ts.get_batch_stock_quotes(symbols=('MSFT', 'FB', 'AAPL'))

In [27]:
data, met= ts.get_daily('ddddd', outputsize='full')

KeyError: 'Time Series (Daily)'

In [26]:
data

            1. open   2. high    3. low  4. close   5. volume
date
1998-01-02  129.630  131.5000  129.5000    131.13   4968500.0
1998-01-05  131.250  133.6300  127.8700    130.38  10047200.0
1998-01-06  129.750  133.0000  129.2500    131.13   8479300.0
1998-01-07  129.880  131.1900  127.5000    129.56   7686600.0
1998-01-08  128.630  132.1300  127.5000    130.50   9702400.0
1998-01-09  130.060  131.5000  125.8700    127.00  10941800.0
1998-01-12  124.620  130.0000  124.3700    129.50   9799200.0
1998-01-13  129.500  132.2500  128.1300    132.13   8368200.0
1998-01-14  132.130  132.5000  129.2500    131.13   6846800.0
1998-01-15  130.380  133.0000  129.8800    132.31   6327800.0
1998-01-16  132.380  135.3800  132.3100    135.25   9117900.0
1998-01-20  134.130  138.0000  134.0000    137.81   8119500.0
1998-01-21  137.250  138.4400  135.6300    137.00  10695900.0
1998-01-22  135.560  139.8800  135.3100    138.63  19892400.0
1998-01-23  138.750  139.4400  136.7000    138.25   7914000.0
1998-01-26  139.880  141.8800  138.4500    141.75   9284700.0
1998-01-27  142.380  145.8800  141.5600    145.19  12192600.0
1998-01-28  146.250  149.5000  145.5000    149.00   9923400.0
1998-01-29  148.940  150.1300  147.5000    148.25   9196400.0
1998-01-30  148.630  150.0000  147.6300    149.19   6258900.0
1998-02-02  151.750  155.1300  150.5000    154.88  12299700.0
1998-02-03  155.130  156.1300  153.8100    155.88   7671800.0
1998-02-04  155.880  158.0000  155.0600    156.81   7742600.0
1998-02-05  158.130  158.7500  154.7500    155.44   8376800.0
1998-02-06  155.380  158.2500  155.1300    158.13   6258800.0
1998-02-09  158.750  158.8800  155.6300    157.19   6835200.0
1998-02-10  157.250  159.5000  156.7500    159.25   6012400.0
1998-02-11  159.380  160.0600  157.0600    158.94   9557500.0
1998-02-12  158.060  158.9400  156.4400    158.75   9582300.0
1998-02-13  158.630  158.7500  157.3800    157.50   5275400.0
...             ...       ...       ...       ...         ...
2019-04-08  119.810  120.0200  118.6400    119.93  15116186.0
2019-04-09  118.630  119.5400  118.5800    119.28  17611981.0
2019-04-10  119.760  120.3500  119.5400    120.19  16477169.0
2019-04-11  120.540  120.8500  119.9200    120.33  14209121.0
2019-04-12  120.640  120.9800  120.3700    120.95  19745143.0
2019-04-15  120.940  121.5800  120.5700    121.05  15792572.0
2019-04-16  121.640  121.6500  120.1000    120.77  14071787.0
2019-04-17  121.240  121.8500  120.5400    121.77  19300938.0
2019-04-18  122.190  123.5200  121.3018    123.37  27990998.0
2019-04-22  122.620  124.0000  122.5700    123.76  15648724.0
2019-04-23  124.100  125.5800  123.8300    125.44  24025521.0
2019-04-24  125.790  125.8500  124.5200    125.01  31256980.0
2019-04-25  130.060  131.3700  128.8300    129.15  38033892.0
2019-04-26  129.700  130.5152  129.0200    129.89  23654933.0
2019-04-29  129.900  130.1800  129.3500    129.77  16324183.0
2019-04-30  129.810  130.7000  129.3947    130.60  24166503.0
2019-05-01  130.530  130.6500  127.7000    127.88  26821692.0
2019-05-02  127.980  128.0000  125.5200    126.21  27350161.0
2019-05-03  127.360  129.4300  127.2500    128.90  24911126.0
2019-05-06  126.390  128.5600  126.1100    128.15  24239464.0
2019-05-07  126.460  127.1800  124.2200    125.52  36017661.0
2019-05-08  125.440  126.3700  124.7500    125.51  28418996.0
2019-05-09  124.290  125.7900  123.5700    125.50  27235835.0
2019-05-10  124.910  127.9300  123.8200    127.13  30915084.0
2019-05-13  124.110  125.5500  123.0400    123.35  33944923.0
2019-05-14  123.870  125.8800  123.7000    124.73  25266315.0
2019-05-15  124.260  126.7100  123.7000    126.02  24722708.0
2019-05-16  126.750  129.3800  126.4600    128.93  30112216.0
2019-05-17  128.305  130.4600  127.9200    128.07  25770539.0
2019-05-20  126.520  127.5825  125.7700    127.06   9618081.0

[5379 rows x 5 columns]

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import io

In [2]:
content = requests.get('https://www.ishares.com/us/products/239726/ishares-core-sp-500-etf/1467271812596.ajax?fileType=csv&fileName=IVV_holdings&dataType=fund&asOfDate=20190329')

In [14]:
business_month_end

Timestamp('1993-11-30 00:00:00')

In [11]:
business_month_end = pd.to_datetime('1993-12-17') + pd.offsets.BMonthEnd(-1)

In [16]:
business_month_end.date().strftime("%Y%m%d")

'19931130'

In [8]:
df = pd.read_csv(io.StringIO(content.text), skiprows=10)

In [10]:
df['Ticker'].values

array(['MSFT', 'AAPL', 'AMZN', 'FB', 'BRKB', 'JNJ', 'GOOG', 'GOOGL',
       'XOM', 'JPM', 'V', 'PG', 'BAC', 'VZ', 'INTC', 'CSCO', 'UNH', 'PFE',
       'CVX', 'T', 'HD', 'MRK', 'MA', 'BA', 'WFC', 'DIS', 'CMCSA', 'KO',
       'PEP', 'NFLX', 'C', 'MCD', 'ABT', 'WMT', 'PM', 'ORCL', 'ADBE',
       'IBM', 'MDT', 'PYPL', 'CRM', 'UNP', 'DWDP', 'MMM', 'AVGO', 'ABBV',
       'AMGN', 'HON', 'ACN', 'LLY', 'TMO', 'NVDA', 'MO', 'COST', 'NKE',
       'UTX', 'TXN', 'LIN', 'NEE', 'SBUX', 'LOW', 'GE', 'AMT', 'GILD',
       'DHR', 'BKNG', 'CAT', 'BMY', 'UPS', 'COP', 'AXP', 'LMT', 'ANTM',
       'USB', 'MDLZ', 'CVS', 'ADP', 'QCOM', 'INTU', 'BDX', 'CELG', 'TJX',
       'GS', 'DUK', 'ISRG', 'CB', 'D', 'CI', 'SYK', 'SLB', 'CHTR', 'CL',
       'CME', 'CSX', 'SPG', 'PNC', 'EOG', 'MS', 'SO', 'BSX', 'CCI',
       'SPGI', 'BLK', 'RTN', 'DE', 'WBA', 'SCHW', 'NSC', 'OXY', 'GM',
       'EXC', 'ZTS', 'MMC', 'VRTX', 'BIIB', 'MU', 'GD', 'NOC', 'AGN',
       'ILMN', 'PLD', 'ECL', 'BK', 'FDX', 'ICE', 'ITW', 'KMB', 'EMR',
       'PGR', 'TGT', 'APD', 'CTSH', 'AEP', 'AON', 'MET', 'WM', 'MPC',
       'PSX', 'EW', 'KMI', 'ADI', 'BAX', 'COF', 'EQIX', 'AMAT', 'PRU',
       'AIG', 'AFL', 'FIS', 'TRV', 'EL', 'HUM', 'XTSLA', 'BBT', 'ROP',
       'VLO', 'MAR', 'SHW', 'HCA', 'WMB', 'ATVI', 'FISV', 'SRE', 'ROST',
       'F', 'ETN', 'ADSK', 'JCI', 'PSA', 'RHT', 'XLNX', 'REGN', 'EBAY',
       'DAL', 'SYY', 'DG', 'ALL', 'GIS', 'YUM', 'EA', 'ORLY', 'ALXN',
       'PEG', 'WELL', 'MCO', 'HPQ', 'STZ', 'XEL', 'OKE', 'VFC', 'APH',
       'EQR', 'AVB', 'ED', 'TEL', 'LRCX', 'PPG', 'ZBH', 'STI', 'IR',
       'GLW', 'LUV', 'HAL', 'LYB', 'PXD', 'PAYX', 'A', 'AZO', 'DLTR',
       'WEC', 'STT', 'DLR', 'FTV', 'HLT', 'ADM', 'TWTR', 'PCAR', 'TROW',
       'DFS', 'MSI', 'PPL', 'IQV', 'VTR', 'CMI', 'DTE', 'WLTW', 'ES',
       'SBAC', 'AMD', 'APC', 'MCK', 'O', 'CXO', 'PH', 'TDG', 'CNC',
       'VRSK', 'MTB', 'GPN', 'USD', 'MNST', 'HPE', 'FLT', 'FE', 'ROK',
       'BXP', 'ALGN', 'SYF', 'SWK', 'CLX', 'APTV', 'TSN', 'KHC', 'CCL',
       'EIX', 'KLAC', 'INFO', 'WY', 'RCL', 'KR', 'MCHP', 'NTRS', 'ULTA',
       'FITB', 'BLL', 'IDXX', 'VRSN', 'NEM', 'HRS', 'ESS', 'AWK', 'AME',
       'FCX', 'MKC', 'CERN', 'IP', 'FAST', 'ETR', 'AEE', 'WAT', 'MTD',
       'UAL', 'HIG', 'NUE', 'CDNS', 'AMP', 'CHD', 'DXC', 'SNPS', 'RSG',
       'CTAS', 'NTAP', 'CMG', 'MSCI', 'BBY', 'FRC', 'CBS', 'LLL', 'ANET',
       'KEYS', 'GPC', 'OMC', 'ARE', 'KEY', 'HSY', 'CMS', 'FANG', 'VMC',
       'CNP', 'TSS', 'INCY', 'HES', 'ANSS', 'CBRE', 'HCP', 'LH', 'RMD',
       'CFG', 'DRI', 'EVRG', 'SYMC', 'MYL', 'COO', 'MXIM', 'K', 'AJG',
       'EFX', 'CAH', 'SWKS', 'XYL', 'RF', 'BHGE', 'TFX', 'DHI', 'WDC',
       'LEN', 'HST', 'EXPE', 'DVN', 'MRO', 'DOV', 'IT', 'WCG', 'CAG',
       'GWW', 'L', 'SJM', 'HBAN', 'CINF', 'IFF', 'MGM', 'EXPD', 'FOXA',
       'HOLX', 'ABMD', 'EXR', 'PFG', 'VAR', 'APA', 'AAL', 'CE', 'MLM',
       'UDR', 'CTXS', 'STX', 'ABC', 'MAA', 'AAP', 'FTNT', 'CPRT', 'AES',
       'NBL', 'LNC', 'HRL', 'NRG', 'NCLH', 'ATO', 'BR', 'TXT', 'DGX',
       'CHRW', 'VNO', 'TSCO', 'AKAM', 'KMX', 'KSU', 'SIVB', 'MAS', 'CMA',
       'TIF', 'ETFC', 'KSS', 'WYNN', 'CTL', 'UHS', 'LNT', 'TAP', 'REG',
       'XRAY', 'COG', 'DRE', 'LW', 'NI', 'TTWO', 'EMN', 'GRMN', 'PKI',
       'PNW', 'JKHY', 'CBOE', 'FRT', 'WAB', 'FMC', 'NDAQ', 'IRM', 'RJF',
       'NOV', 'FTI', 'HAS', 'VIAB', 'BEN', 'WRK', 'MOS', 'AVY', 'FFIV',
       'PKG', 'PVH', 'TPR', 'HSIC', 'JNPR', 'DISCK', 'CF', 'URI', 'BFB',
       'JBHT', 'LKQ', 'JEC', 'RE', 'HII', 'ALB', 'SNA', 'QRVO', 'ALLE',
       'NLSN', 'TMK', 'ZION', 'WHR', 'IPG', 'ARNC', 'WU', 'BWA', 'KIM',
       'ADS', 'MHK', 'HFC', 'RHI', 'IVZ', 'AOS', 'AIV', 'SLG', 'M', 'UNM',
       'SEE', 'CPB', 'XEC', 'CPRI', 'ALK', 'PHM', 'DVA', 'PNR', 'RL',
       'FL', 'FBHS', 'HBI', 'PBCT', 'FLIR', 'XRX', 'DISH', 'HP', 'ROL',
       'NWL', 'FLS', 'PRGO', 'AIZ', 'FOX', 'AMG', 'GPS', 'HOG', 'LEG',
       'IPGP', 'PWR', 'COTY', 'FLR', 'TRIP', 'LB', 'HRB', 'JWN', 'JEF',
       'NWSA', 'MAC', 'MAT', 'DISCA', 'BHF', 'UAA', 'NKTR', 'UA', 'UBFUT',
       'NWS', 'ESM9', '\xa0'], dtype=object)